# Generated by Django 3.1.4 on 2020-12-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_valid_access_token',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shorted_acess_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
