# Generated by Django 3.1.4 on 2020-12-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201204_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_valid_access_token',
            field=models.BooleanField(default=False),
        ),
    ]
