# Generated by Django 3.1.4 on 2020-12-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20201213_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='shorted_acess_token',
            new_name='shorted_access_token',
        ),
    ]
