# Generated by Django 3.1.4 on 2020-12-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_auto_20201204_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('publish', 'Kích hoạt'), ('disable', 'Không kích hoạt')], default='disable', max_length=10)),
                ('fb_id', models.CharField(max_length=50, null=True, unique=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan_count', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('customer', models.ManyToManyField(to='customer.Customer')),
            ],
        ),
    ]
