# Generated by Django 3.1.4 on 2020-12-17 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', enumfields.fields.EnumField(default='disable', enum=page.models.PageStatus, max_length=10, verbose_name='status')),
                ('name', models.CharField(max_length=255, verbose_name='page_name')),
                ('fb_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='page_fb_id')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='page_access_token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('fan_count', models.IntegerField(default=0, verbose_name='fan_count')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='page/', verbose_name='avatar')),
                ('customers', models.ManyToManyField(related_name='pages', to='customer.Customer', verbose_name='customer')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='feed_fb_id')),
                ('message', models.TextField(blank=True, null=True, verbose_name='messgae')),
                ('permalink_url', models.SlugField(blank=True, null=True, verbose_name='permalink_url')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_time')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='page.page', verbose_name='page')),
            ],
        ),
    ]
