# Generated by Django 3.1.4 on 2020-12-17 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', enumfields.fields.EnumField(default='disable', enum=page.models.PageStatus, max_length=10, verbose_name='status')),
                ('name', models.CharField(max_length=255)),
                ('fb_id', models.CharField(max_length=50, null=True, unique=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan_count', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('customers', models.ManyToManyField(related_name='pages', to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('permalink_url', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='page.page')),
            ],
        ),
    ]
