# Generated by Django 3.1.4 on 2020-12-17 16:53

from django.db import migrations, models
import django.utils.timezone
import enumfields.fields
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('page', '0002_auto_20201217_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='page',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='page',
            name='customers',
            field=models.ManyToManyField(related_name='pages', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='page',
            name='fan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='fb_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=enumfields.fields.EnumField(default='disable', enum=page.models.PageStatus, max_length=10),
        ),
    ]
