# Generated by Django 3.1.4 on 2020-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='fb_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
