# Generated by Django 3.1.4 on 2020-12-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201204_1151'),
        ('page', '0004_auto_20201204_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='customers',
            field=models.ManyToManyField(related_name='pages', to='customer.Customer'),
        ),
    ]
